---
bot_token: 1234567890:ABcdefghigklmnopqrstuvwxyz123456789  # telegram bot token
webhook_url: https://example.com/api/  # wehook url which is routed to app
listen_port: "9000"  # internal port app listen on
report_channel: -100123456789  # channel id for bug reports
admin: 123456789  # telegram user id for admin
users:  # map of authorized users
    987654321: user  # key is user id, value is arbitrary name for convenience
    654123789: another user  # name can be with spaces
    123456789: admin  # you can add admin here to access user commands
inkotools_api_url: http://127.0.0.1:9999/  # url to inkotools api service
debug: false  # enable debug logging
...
